//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _17_10_2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public int ID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime StopDate { get; set; }
        public string Reason { get; set; }
        public int ErrorType { get; set; }
        public int UserID { get; set; }
    
        public virtual ErrorTypes ErrorTypes { get; set; }
        public virtual Users Users { get; set; }

        public System.TimeSpan TimeSpend
        {
            get
            {
                return StopDate - StartDate;
            }
        }

        public System.DateTime date
        {
            get
            {
                return StartDate.Date;
            }
        }

        public TimeSpan loginTime
        {
            get
            {
                return StartDate.TimeOfDay;
            }
        }

        public TimeSpan logoutTime
        {
            get
            {
                return StopDate.TimeOfDay;
            }
        }
    }
}
